# 模板引擎目录
viewpath = "/home/www/templates/"
name = "hello world!"
# 日志配置
[logger]
    # 日志目录
    path   = "logs"
    # 	all LEVEL_ALL  = LEVEL_DEBU | LEVEL_INFO | LEVEL_NOTI | LEVEL_WARN | LEVEL_ERRO | LEVEL_CRIT
    #	dev LEVEL_DEV  = LEVEL_ALL
    #	pro LEVEL_PROD = LEVEL_WARN | LEVEL_ERRO | LEVEL_CRIT
    level  = "all"
    # 是否打印到控制台
    stdout = true

# MySQL数据库配置
[database]
    [[database.default]]
        host     = "127.0.0.1"
        port     = 3306
        user     = "root"
        pass     = "123456"
        name     = "test1"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"
    [[database.default]]
        host     = "127.0.0.1"
        port     = "3306"
        user     = "root"
        pass     = "123456"
        name     = "test2"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"
# Redis数据库配置
[redis]
    disk  = "127.0.0.1:6379,0"
    cache = "127.0.0.1:6379,1"